version: 2
updates:
  # Homebrew packages
  - package-ecosystem: "bundler"
    directory: "/stow/brew"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "⬆️"
      include: "scope"

  # Node.js packages in Raycast extensions
  - package-ecosystem: "npm"
    directory: "/raycast/extensions/clipboard-to-markdown-code-block"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "⬆️"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "⬆️"
      include: "scope"
