console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    foreground = 'yellow'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '{{ .HEAD }}{{ if .Staging.Changed }}  <b>{{ .Staging.String }}</b>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}'
  foreground = 'black'
  background = 'magenta'
  type = 'git'
  style = 'diamond'
  tips = ['git', 'g']

  [tooltips.properties]
    fetch_status = true
    fetch_upstream_icon = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '{{.Context}}<b>{{if .Namespace}}</b>::<b>{{.Namespace}}</b>{{end}} :: {{.User}}@{{.Cluster}}'
  foreground = 'black'
  background = 'magenta'
  type = 'kubectl'
  style = 'diamond'
  tips = ['kubectl', 'k', 'ka', 'k9s', 'stern']

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '{{if .Env.SCOOTER_PROFILE}}SCOOTER_PROFILE=<b>{{.Env.SCOOTER_PROFILE}}</b>{{else}}NO PROFILE{{end}}'
  foreground = 'black'
  background = 'magenta'
  type = 'text'
  style = 'diamond'
  tips = ['scooter']

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  foreground = 'black'
  background = 'magenta'
  type = 'docker'
  style = 'diamond'
  tips = ['docker']
