#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

# based on https://github.com/dreamsofautonomy/zen-omp/blob/main/zen.toml

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'

    [blocks.segments.properties]
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '

[[tooltips]]
type = "git"
tips = [ "git", "g" ]
style = "diamond"
foreground = "black"
background = "magenta"
leading_diamond = ""
trailing_diamond = ""
template = "{{ .HEAD }}{{ if .Staging.Changed }}  <b>{{ .Staging.String }}</b>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}"

  [tooltips.properties]
  fetch_status = true
  fetch_upstream_icon = true

[[tooltips]]
type = "kubectl"
tips = [ "kubectl", "k", "ka", "k9s", "stern" ]
style = "diamond"
foreground = "black"
background = "magenta"
leading_diamond = ""
trailing_diamond = ""
template = "{{.Context}}<b>{{if .Namespace}}</b>::<b>{{.Namespace}}</b>{{end}} :: {{.User}}@{{.Cluster}}"

[[tooltips]]
type = "text"
tips = [ "scooter" ]
style = "diamond"
foreground = "black"
background = "magenta"
leading_diamond = ""
trailing_diamond = ""
template = "{{if .Env.SCOOTER_PROFILE}}SCOOTER_PROFILE=<b>{{.Env.SCOOTER_PROFILE}}</b>{{else}}NO PROFILE{{end}}"


