name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and validate
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install markdownlint-cli2
      run: npm install -g markdownlint-cli2
    
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    
    - name: Lint markdown files
      run: markdownlint-cli2 "**/*.md"
    
    - name: Lint shell scripts
      run: |
        find . -type f -name "*.sh" -not -path "./external/*" -not -path "./raycast/extensions/*/node_modules/*" | \
        xargs shellcheck -x --severity=warning
    
    - name: Validate setup scripts
      run: |
        echo "Validating setup scripts syntax..."
        bash -n bin/setup.sh
        bash -n bin/setup-stow.sh || echo "setup-stow.sh not found, skipping"
    
    - name: Check for TODO/FIXME comments
      run: |
        if grep -r "TODO\|FIXME" --include="*.sh" --include="*.zsh" --include="*.md" --exclude-dir=external --exclude-dir=node_modules . ; then
          echo "Found TODO/FIXME comments - consider addressing them"
          exit 0  # Don't fail the build for this
        fi
    
    - name: Validate Raycast extensions
      run: |
        for ext_dir in raycast/extensions/*/; do
          if [ -f "$ext_dir/package.json" ]; then
            echo "Validating $ext_dir"
            cd "$ext_dir"
            npm ci
            npm run build || npm run typecheck || echo "No build/typecheck script found"
            cd - > /dev/null
          fi
        done